    
language: python
python:
  - "3.5"  # 3.7 development branch
cache: pip
before_install:
  - pip uninstall enigma-catalyst
  - pip install enigma-catalyst
  - pip install mysql-connector-python
install:
  - pip install -r requirements.txt
script:
  - python3 test_script.py
